package views;

import javax.swing.JButton;
import javax.swing.JTextField;

public class AddCircleDialog extends javax.swing.JDialog {
    
  public JTextField getDiameterField() {
    return diameter;
  }
  public JTextField getStrokeWidthField() {
    return strokeWidth;
  }
  public JTextField getLineColorField() {
    return lineColor;
  }
  public JTextField getFillColorField() {
    return fillColor;
  }
  public JTextField getTitleField() {
    return title;
  }
  public JButton getChooseLineColor() {
    return chooseLineColor;
  }
  public JButton getChooseFillColor() {
    return chooseFillColor;
  }
  public JButton getAddButton() {
    return add;
  }
  public JButton getCancelButton() {
    return cancel;
  }

  /**
   * Creates new form AddCircleDialog
   * @param parent
   * @param modal
   */
  public AddCircleDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    diameterLabel = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lineColorLabel = new javax.swing.JLabel();
    fillColorLabel = new javax.swing.JLabel();
    titleLabel = new javax.swing.JLabel();
    strokeWidthLabel = new javax.swing.JLabel();
    diameter = new javax.swing.JTextField();
    strokeWidth = new javax.swing.JTextField();
    lineColor = new javax.swing.JTextField();
    fillColor = new javax.swing.JTextField();
    title = new javax.swing.JTextField();
    add = new javax.swing.JButton();
    chooseLineColor = new javax.swing.JButton();
    chooseFillColor = new javax.swing.JButton();
    cancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    diameterLabel.setText("Diameter");

    lineColorLabel.setText("line color:");

    fillColorLabel.setText("fill color:");

    titleLabel.setText("title:");

    strokeWidthLabel.setText("stroke width:");

    lineColor.setEditable(false);
    lineColor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lineColorActionPerformed(evt);
      }
    });

    fillColor.setEditable(false);

    add.setText("Add");
    add.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addActionPerformed(evt);
      }
    });

    chooseLineColor.setText("Choose");
    chooseLineColor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chooseLineColorActionPerformed(evt);
      }
    });

    chooseFillColor.setText("Choose");

    cancel.setText("Cancel");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(136, 136, 136)
            .addComponent(add)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cancel))
          .addGroup(layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(strokeWidthLabel)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineColorLabel))
              .addComponent(fillColorLabel)
              .addComponent(titleLabel)
              .addComponent(diameterLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(strokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(diameter, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lineColor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseLineColor))
              .addGroup(layout.createSequentialGroup()
                .addComponent(fillColor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseFillColor))
              .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(58, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(diameterLabel)
          .addComponent(diameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(strokeWidthLabel)
          .addComponent(strokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lineColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lineColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(chooseLineColor)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(fillColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(chooseFillColor))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(titleLabel))
            .addGap(97, 97, 97)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(add)
              .addComponent(cancel)))
          .addComponent(fillColorLabel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_addActionPerformed

  private void lineColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineColorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_lineColorActionPerformed

  private void chooseLineColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLineColorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_chooseLineColorActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton add;
  private javax.swing.JButton cancel;
  private javax.swing.JButton chooseFillColor;
  private javax.swing.JButton chooseLineColor;
  private javax.swing.JTextField diameter;
  private javax.swing.JLabel diameterLabel;
  private javax.swing.JTextField fillColor;
  private javax.swing.JLabel fillColorLabel;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField lineColor;
  private javax.swing.JLabel lineColorLabel;
  private javax.swing.JTextField strokeWidth;
  private javax.swing.JLabel strokeWidthLabel;
  private javax.swing.JTextField title;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables
}
