package views;

import javax.swing.*;

public class FigureFrame extends javax.swing.JFrame {
  public Canvas getCanvas() {
    return (Canvas) canvas;
  }
  public JComboBox getFigureList() {
    return figureList;
  }
  public JSpinner getScaleSpinner() {
    return scale;
  }
  public JMenuItem getLoadSamples() {
    return loadSamples;
  }
  public JMenuItem getLoad() {
    return Load;
  }
  public JMenuItem getSave() {
    return Save;
  }
  public JMenuItem getAddRectDialog() {
    return addRectDialog;
  }
  public JMenuItem getAddCircleDialog() {
    return Circle;
  }
  public JButton getMoveToTop() {
    return moveToTopButton;
  }
  public JButton getRemove() {
    return removeButton;
  }
  

  /**
   * Creates new form MyFrame
   */
  public FigureFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    canvas = new Canvas();
    jPanel2 = new javax.swing.JPanel();
    moveToTopButton = new javax.swing.JButton();
    removeButton = new javax.swing.JButton();
    figureList = new javax.swing.JComboBox<>();
    scale = new javax.swing.JSpinner();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    loadSamples = new javax.swing.JMenuItem();
    Load = new javax.swing.JMenuItem();
    Save = new javax.swing.JMenuItem();
    addCircleDialog = new javax.swing.JMenu();
    addRectDialog = new javax.swing.JMenuItem();
    Circle = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    canvas.setEditable(false);
    canvas.setColumns(20);
    canvas.setRows(5);
    jScrollPane1.setViewportView(canvas);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    moveToTopButton.setText("Move To Top");
    jPanel2.add(moveToTopButton);

    removeButton.setText("Remove");
    jPanel2.add(removeButton);

    figureList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jPanel2.add(figureList);
    jPanel2.add(scale);

    getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

    jMenu1.setText("File");

    loadSamples.setText("Load Samples");
    loadSamples.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loadSamplesActionPerformed(evt);
      }
    });
    jMenu1.add(loadSamples);

    Load.setText("Load");
    Load.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        LoadActionPerformed(evt);
      }
    });
    jMenu1.add(Load);

    Save.setText("Save");
    Save.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SaveActionPerformed(evt);
      }
    });
    jMenu1.add(Save);

    jMenuBar1.add(jMenu1);

    addCircleDialog.setText("Figures");

    addRectDialog.setText("Add Rectangle");
    addRectDialog.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addRectDialogActionPerformed(evt);
      }
    });
    addCircleDialog.add(addRectDialog);

    Circle.setText("Add Circle");
    Circle.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        CircleActionPerformed(evt);
      }
    });
    addCircleDialog.add(Circle);

    jMenuBar1.add(addCircleDialog);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void addRectDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRectDialogActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_addRectDialogActionPerformed

  private void CircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_CircleActionPerformed

  private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_SaveActionPerformed

  private void loadSamplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSamplesActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_loadSamplesActionPerformed

  private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_LoadActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem Circle;
  private javax.swing.JMenuItem Load;
  private javax.swing.JMenuItem Save;
  private javax.swing.JMenu addCircleDialog;
  private javax.swing.JMenuItem addRectDialog;
  private javax.swing.JTextArea canvas;
  private javax.swing.JComboBox<String> figureList;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JMenuItem loadSamples;
  private javax.swing.JButton moveToTopButton;
  private javax.swing.JButton removeButton;
  private javax.swing.JSpinner scale;
  // End of variables declaration//GEN-END:variables
}
